name: deploy
on:
  push:
    branches: [master]
jobs:
  reapack-index:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Configure git
      run: |-
        git config user.name  'D34dmeat'
        git config user.email 'd34dmeat@gmail.com'
    - name: Install Pandoc
      run:  sudo apt-get install -yy pandoc
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
    - name: Install reapack-index
      run:  gem install reapack-index
    - name: Update index.xml
      run:  reapack-index --commit
    - name: Push changes
      run:  git push
